language: php
php:
  - 5.5.21
  - 5.6.0
  - 5.6.1
  - 5.6.2
  - 5.6.3
  - 5.6.4
  - 5.6.5
  - 5.6.6
  - 5.6.7
  - 5.6.8
  - 5.6.9
  - 5.6.9
  - 5.6.10
  - 5.6.11
  - 5.6.12
  - 5.6.13
  - 5.6.14
  - 5.6.15
  - 5.6.16
  - 5.6.17
  - 5.6.18
  - 5.6.19
  - 5.6.20
  - 5.6.21
  - 5.6.22
  - 5.6.23
  - 5.6.24
  - 5.6.25
  - 5.6.26
  - 5.6.27
  - 5.6.28
  - 5.6.29
  - 5.6.30
  - 5.6
  - 7.0.0
  - 7.0.1
  - 7.0.2
  - 7.0.3
  - 7.0.4
  - 7.0.5
  - 7.0.6
  - 7.0.7
  - 7.0.8
  - 7.0.9
  - 7.0.10
  - 7.0.11
  - 7.0.12
  - 7.0.13
  - 7.0.14
  - 7.0.15
  - 7.0
  - 7.1.0
  - 7.1.1
  - 7.1
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
script:
  - composer create-project --no-interaction bear/skeleton app
  - cd app
  - touch .env
  - vendor/bin/phpunit
  - php bootstrap/web.php get /
